version: 2.1

orbs:
  python: circleci/python@1.3.3
  azure-cli: circleci/azure-cli@1.1.0
  azure-acr: circleci/azure-acr@0.2.0

workflows:
  test-build-push-image:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest 
      - verify-install:
          executor: azure-cli/default
          steps:
            - azure-cli/install
            - run:
                command: az -v
                name: Verify Azure CLI is installed
      - login-to-azure:
        executor: azure-cli/default
        steps:
        - azure-cli/install
          # - azure-cli/login-with-user:
          #     alternate-tenant: true
        - run:
            command: az resource list
            name: List resources of tenant stored as `AZURE_TENANT` env var
      - azure-acr/build-and-push-image:
          login-server-name: devopsupskillCR.azurecr.io
          registry-name: devopsupskillCR
          repo: devops-bookstore-api
          tag: '1.$CIRCLE_BUILD_NUM'
          requires:
            - "python/test"
            - "verify-install"
            - "login-to-az"
